name: flutter_gravatar
description: Flutter/Dart package to easily build url for Gravatar images and profiles
version: 2.0.1-nullsafety.1
homepage: https://github.com/beerstorm-net/flutter_gravatar

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  crypto: ^3.0.0

#dependency_overrides:
#  typed_data: ^1.3.0